//! Generated helper scripts for Walker/Elephant menus.

use std::fs;
use std::path::PathBuf;

use crate::config::LaeConfig;
use crate::error::{LaeError, Result};
use crate::xdg::ensure_parent;

pub fn bin_dir(cfg: &LaeConfig) -> PathBuf {
    cfg.install_hypr_share_dir.join("bin")
}

pub fn write_menu_helper(cfg: &LaeConfig) -> Result<PathBuf> {
    let dest_dir = bin_dir(cfg);
    ensure_parent(&dest_dir.join("_"))?;
    fs::create_dir_all(&dest_dir).map_err(|source| LaeError::Write {
        path: dest_dir.clone(),
        source,
    })?;
    let lae_bin = dest_dir.join("lae");
    let helper = dest_dir.join("lae-task-menu-json");
    let body = format!(
        r#"#!/usr/bin/env bash
# Generated by lae install — do not edit
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
export LAE="{lae}"
exec "$LAE" task menu-json
"#
        ,
        lae = lae_bin.display()
    );
    fs::write(&helper, body).map_err(|source| LaeError::Write {
        path: helper.clone(),
        source,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&helper)
            .map_err(|source| LaeError::Read {
                path: helper.clone(),
                source,
            })?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&helper, perms).map_err(|source| LaeError::Write {
            path: helper.clone(),
            source,
        })?;
    }
    Ok(helper)
}
