"""Install helper scripts with absolute Python path for Walker/Elephant."""

from __future__ import annotations

import os
import sys
from pathlib import Path

from lae.core.config import LaeConfig, load_config


def bin_dir(cfg: LaeConfig | None = None) -> Path:
    cfg = cfg or load_config()
    return cfg.install_hypr_share_dir / "bin"


def write_menu_helper(cfg: LaeConfig | None = None) -> Path:
    """Script Walker/Elephant can call without relying on lae being on PATH."""
    cfg = cfg or load_config()
    dest_dir = bin_dir(cfg)
    dest_dir.mkdir(parents=True, exist_ok=True)
    helper = dest_dir / "lae-task-menu-json"
    python = sys.executable
    lae_bin = dest_dir / "lae"
    helper.write_text(
        f"""#!/usr/bin/env bash
# Generated by lae install — do not edit
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
export LAE="{lae_bin}"
exec {python} - <<'PY'
import os
from lae.daemon.service import TaskService

lae = os.environ["LAE"]
items = TaskService().tasks_for_menu()
for t in items:
    kind = t.get("kind", "task")
    if kind == "default":
        action = f"{{lae}} taskspace default"
        label = "default"
    else:
        action = f"{{lae}} task switch {{t['id']}}"
        label = t.get("name") or t["id"]
    if t.get("current"):
        label += " (active)"
    workspaces = ", ".join(t.get("workspaces", t.get("desktops", [])))
    status = t.get("status", "")
    print("\\t".join([label, workspaces, status, action]))
PY
"""
    )
    helper.chmod(0o755)
    return helper


def write_lae_wrapper(cfg: LaeConfig | None = None) -> Path:
    """Wrapper so hyprland exec and scripts can invoke lae without PATH."""
    cfg = cfg or load_config()
    dest_dir = bin_dir(cfg)
    dest_dir.mkdir(parents=True, exist_ok=True)
    wrapper = dest_dir / "lae"
    python = sys.executable
    wrapper.write_text(
        f"""#!/usr/bin/env bash
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
exec {python} -m lae.cli.main "$@"
"""
    )
    wrapper.chmod(0o755)
    return wrapper
