"""Install helper scripts for Hyprland keybinds and Waybar."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from lae.core.config import LaeConfig, load_config


def bin_dir(cfg: LaeConfig | None = None) -> Path:
    cfg = cfg or load_config()
    return cfg.install_hypr_share_dir / "bin"


def write_tui_launch_helper(cfg: LaeConfig | None = None) -> Path:
    """Launch the task manager TUI in the user's terminal."""
    cfg = cfg or load_config()
    dest_dir = bin_dir(cfg)
    dest_dir.mkdir(parents=True, exist_ok=True)
    helper = dest_dir / "lae-task-tui"
    lae_bin = dest_dir / "lae"
    helper.write_text(
        f"""#!/usr/bin/env bash
# Generated by lae install — do not edit
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
export LAE="{lae_bin}"
exec "$LAE" task tui-launch
"""
    )
    helper.chmod(0o755)
    return helper


def write_waybar_helper(cfg: LaeConfig | None = None) -> Path:
    """Minimal stdlib script for Waybar exec — reads shared module cache."""
    cfg = cfg or load_config()
    dest_dir = bin_dir(cfg)
    dest_dir.mkdir(parents=True, exist_ok=True)
    helper = dest_dir / "lae-waybar-json"
    lae_bin = dest_dir / "lae"
    helper.write_text(
        f'''#!/usr/bin/env python3
# Generated by lae install — do not edit
import fcntl
import json
import os
import sys
import time
from pathlib import Path

MAX_AGE = 5.0
LAE = {json.dumps(str(lae_bin))}


def runtime_dir() -> Path:
    base = os.environ.get("XDG_RUNTIME_DIR")
    if not base:
        base = f"/run/user/{{os.getuid()}}"
    return Path(base) / "lae"


def cache_path() -> Path:
    return runtime_dir() / "waybar-modules.json"


def lock_path() -> Path:
    return runtime_dir() / "waybar.refresh.lock"


def module_key() -> str:
    if sys.argv[1] == "task":
        return "task"
    return f"workspace-{{sys.argv[2]}}"


def cache_age() -> float | None:
    path = cache_path()
    if not path.is_file():
        return None
    return time.time() - path.stat().st_mtime


def cache_is_stale() -> bool:
    age = cache_age()
    return age is None or age > MAX_AGE


def read_cache(*, allow_stale: bool = True) -> dict | None:
    path = cache_path()
    if not path.is_file():
        return None
    if not allow_stale and cache_is_stale():
        return None
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def ensure_fresh_cache() -> None:
    if not cache_is_stale():
        return
    import subprocess

    runtime = runtime_dir()
    runtime.mkdir(parents=True, exist_ok=True)
    lock = lock_path().open("w")
    try:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            owns_refresh = True
        except BlockingIOError:
            owns_refresh = False
        if owns_refresh:
            if cache_is_stale():
                env = os.environ.copy()
                env.setdefault("XDG_RUNTIME_DIR", str(runtime.parent))
                subprocess.run(
                    [LAE, "waybar", "refresh-cache"],
                    check=False,
                    env=env,
                )
        else:
            fcntl.flock(lock, fcntl.LOCK_SH)
    finally:
        fcntl.flock(lock, fcntl.LOCK_UN)
        lock.close()
        try:
            lock_path().unlink(missing_ok=True)
        except OSError:
            pass


def main() -> None:
    key = module_key()
    fallback = (read_cache(allow_stale=True) or {{}}).get(key)
    if fallback and not cache_is_stale():
        payload = fallback
    else:
        if cache_is_stale():
            ensure_fresh_cache()
        payload = (read_cache(allow_stale=True) or {{}}).get(key) or fallback
    if not payload:
        payload = {{"text": "", "class": "hidden"}}
    sys.stdout.write(json.dumps(payload, separators=(",", ":")))


if __name__ == "__main__":
    main()
'''
    )
    helper.chmod(0o755)
    return helper


def write_lae_wrapper(cfg: LaeConfig | None = None) -> Path:
    """Wrapper so hyprland exec and scripts can invoke lae without PATH."""
    cfg = cfg or load_config()
    dest_dir = bin_dir(cfg)
    dest_dir.mkdir(parents=True, exist_ok=True)
    wrapper = dest_dir / "lae"
    python = sys.executable
    wrapper.write_text(
        f"""#!/usr/bin/env bash
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
exec {python} -m lae.cli.main "$@"
"""
    )
    wrapper.chmod(0o755)
    return wrapper
