//! Generated helper scripts for Hyprland keybinds and Waybar clicks.

use std::fs;
use std::path::PathBuf;

use crate::config::TskConfig;
use crate::error::{TskError, Result};
use crate::xdg::ensure_parent;

pub fn bin_dir(cfg: &TskConfig) -> PathBuf {
    cfg.install_hypr_share_dir.join("bin")
}

pub fn write_install_helpers(cfg: &TskConfig) -> Result<()> {
    let dest_dir = bin_dir(cfg);
    ensure_parent(&dest_dir.join("_"))?;
    fs::create_dir_all(&dest_dir).map_err(|source| TskError::Write {
        path: dest_dir.clone(),
        source,
    })?;
    let tsk_bin = dest_dir.join("tsk");
    write_workspace_switch_helper(cfg, &tsk_bin)?;
    write_workspace_move_helper(cfg, &tsk_bin)?;
    write_tui_launch_helper(cfg, &tsk_bin)?;
    write_terminal_helper(cfg, &tsk_bin)?;
    Ok(())
}

fn write_workspace_switch_helper(cfg: &TskConfig, tsk_bin: &std::path::Path) -> Result<PathBuf> {
    let helper = bin_dir(cfg).join("tsk-workspace-switch");
    let body = format!(
        r#"#!/usr/bin/env bash
# Generated by tsk install — do not edit
# Hyprland switch first (minimal latency), then sync state to tsk.
set -euo pipefail
slot="$1"
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
"{tsk}" workspace dispatch "$slot"
"{tsk}" workspace remember "$slot" >/dev/null 2>&1 &
"#,
        tsk = tsk_bin.display()
    );
    fs::write(&helper, body).map_err(|source| TskError::Write {
        path: helper.clone(),
        source,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&helper)
            .map_err(|source| TskError::Read {
                path: helper.clone(),
                source,
            })?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&helper, perms).map_err(|source| TskError::Write {
            path: helper.clone(),
            source,
        })?;
    }
    Ok(helper)
}

fn write_workspace_move_helper(cfg: &TskConfig, tsk_bin: &std::path::Path) -> Result<PathBuf> {
    let helper = bin_dir(cfg).join("tsk-workspace-move");
    let body = format!(
        r#"#!/usr/bin/env bash
# Generated by tsk install — do not edit
# Move active window to the taskspace-scoped workspace for this slot.
set -euo pipefail
slot="$1"
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
"{tsk}" workspace move-dispatch "$slot"
"#,
        tsk = tsk_bin.display()
    );
    fs::write(&helper, body).map_err(|source| TskError::Write {
        path: helper.clone(),
        source,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&helper)
            .map_err(|source| TskError::Read {
                path: helper.clone(),
                source,
            })?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&helper, perms).map_err(|source| TskError::Write {
            path: helper.clone(),
            source,
        })?;
    }
    Ok(helper)
}

fn write_tui_launch_helper(cfg: &TskConfig, tsk_bin: &std::path::Path) -> Result<PathBuf> {
    let helper = bin_dir(cfg).join("tsk-task-tui");
    let body = format!(
        r#"#!/usr/bin/env bash
# Generated by tsk install — do not edit
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
export TSK="{tsk}"
exec "$TSK" task tui-launch
"#,
        tsk = tsk_bin.display()
    );
    fs::write(&helper, body).map_err(|source| TskError::Write {
        path: helper.clone(),
        source,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&helper)
            .map_err(|source| TskError::Read {
                path: helper.clone(),
                source,
            })?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&helper, perms).map_err(|source| TskError::Write {
            path: helper.clone(),
            source,
        })?;
    }
    Ok(helper)
}

fn write_terminal_helper(cfg: &TskConfig, tsk_bin: &std::path::Path) -> Result<PathBuf> {
    let helper = bin_dir(cfg).join("tsk-terminal");
    let body = format!(
        r#"#!/usr/bin/env bash
# Generated by tsk install — do not edit
export XDG_RUNTIME_DIR="${{XDG_RUNTIME_DIR:-/run/user/$(id -u)}}"
export HOME="${{HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}}"
export TSK="{tsk}"
exec "$TSK" task terminal
"#,
        tsk = tsk_bin.display()
    );
    fs::write(&helper, body).map_err(|source| TskError::Write {
        path: helper.clone(),
        source,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&helper)
            .map_err(|source| TskError::Read {
                path: helper.clone(),
                source,
            })?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&helper, perms).map_err(|source| TskError::Write {
            path: helper.clone(),
            source,
        })?;
    }
    Ok(helper)
}
